//! Defines functions and Structs to use for identity tracking

use sha1_smol::Sha1;

/// Galatea Internal Process ID
#[expect(non_camel_case_types)]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct GA_PID([u8; 16]);

impl GA_PID{
    /// Creates an identity from its canonical bytes.
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Returns the identity bytes for IPC or hashing.
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }

    /// Returns whether this is the reserved zero identity.
    pub fn is_zero(&self) -> bool {
        self.0 == [0; 16]
    }
}

// GALATEA NAMESPACE

const GAPID_NAMESPACE: &str = "fc502cc9-faa2-5e5d-c30a-cb233d3a40f8";

/// Uses PID, lowercase Image Name and Startime (in windows ticks) to generate a consistent traceable PID
// Exists as PIDs are not reliably unique and StartKey seems tricky in usermode
pub fn generate_process_id(pid: u32, image: &[u8], ticks: u64) -> GA_PID {
    let mut hasher = Sha1::new();

    hasher.update(GAPID_NAMESPACE.as_bytes());
    hasher.update(&pid.to_le_bytes());
    hasher.update(image);
    hasher.update(&ticks.to_le_bytes());

    let mut bytes = [0; 16];
    bytes.copy_from_slice(&hasher.digest().bytes()[..16]);

    GA_PID::from_bytes(bytes)
}



// Tests were generated by AI
#[cfg(test)]
mod tests {
    use super::generate_process_id;

    const IMAGE: &[u8] = b"\\Device\\HarddiskVolume3\\Windows\\System32\\cmd.exe";
    const TICKS: u64 = 133_742_000_000_000;

    #[test]
    fn same_process_data_produces_same_id() {
        let first = generate_process_id(4242, IMAGE, TICKS);
        let second = generate_process_id(4242, IMAGE, TICKS);

        assert_eq!(first, second);
    }

    #[test]
    fn pid_changes_id() {
        let first = generate_process_id(4242, IMAGE, TICKS);
        let second = generate_process_id(4243, IMAGE, TICKS);

        assert_ne!(first, second);
    }

    #[test]
    fn image_changes_id() {
        let first = generate_process_id(4242, IMAGE, TICKS);
        let second = generate_process_id(
            4242,
            b"\\Device\\HarddiskVolume3\\Windows\\System32\\powershell.exe",
            TICKS,
        );

        assert_ne!(first, second);
    }

    #[test]
    fn start_time_changes_id() {
        let first = generate_process_id(4242, IMAGE, TICKS);
        let second = generate_process_id(4242, IMAGE, TICKS + 1);

        assert_ne!(first, second);
    }

    #[test]
    fn generated_id_is_not_zero() {
        let id = generate_process_id(4242, IMAGE, TICKS);
        assert!(!id.is_zero());
    }

    #[test]
    fn id_has_128_bits() {
        let id = generate_process_id(4242, IMAGE, TICKS);

        assert_eq!(id.as_bytes().len(), 16);
    }

    #[test]
    fn empty_image_is_supported_deterministically() {
        let first = generate_process_id(4242, b"", TICKS);
        let second = generate_process_id(4242, b"", TICKS);

        assert_eq!(first, second);
    }
}